clone/blog/urls.py
from django.conf.urls import url
from blog import views
app_name="blog"
urlpatterns=[
  url(r'^about/$',views.about.as_view(),name='about'),
  url(r'^$',views.postlist.as_view(),name='postlist'),
  url(r'^post/(?P<pk>\d+)$',views.postdetail.as_view(),name="postdetail"),
  url(r'^post/new/$',views.postcreate.as_view(),name='postnew'),
  url(r'^post/(?P<pk>\d+)/edit/$',views.postupdate.as_view(),name='postedit'),
   url(r'^post/(?P<pk>\d+)/delete/$',views.postdelete.as_view(),name='postdelete'),
   url(r'^drafts/$',views.draftlist.as_view(),name='draftlist'),
   url(r'^post/(?P<pk>\d+)/comment/$',views.add_comment_to_post,name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$',views.comment_approve,name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$',views.comment_remove,name='comment_remove'),
    url(r'^post/(?P<pk>\d+)/publish/$',views.post_publish,name='post_publish'),

]

clone/clone/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.urls import path
from django.contrib.auth import views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'',include("blog.urls")),
    url(r'accounts/logout/$',views.LogoutView.as_view(),name='logout',kwargs={'next_page':'/'}),
    url(r'accounts/login/$',views.LoginView.as_view(),name='login'),
]

clone/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
# Create your models here.
class Post(models.Model):
    title=models.CharField(max_length=256)
    author=models.ForeignKey('auth.User',on_delete=models.CASCADE)
    text=models.TextField()
    create_time=models.DateTimeField(default=timezone.now)
    pub_time=models.DateTimeField(blank=True,null=True)

    def publish(self):
        self.pub_time=timezone.now()
        self.save()

    def approve_comments(self):
        return self.comment.filter(approved_comment=True)

    def get_absolute_url(self):
        return reverse("blog:postdetail",kwargs={'pk':self.pk})


    def __str__(self):
        return self.title


class comment(models.Model):
    post=models.ForeignKey('blog.post',related_name="comment",on_delete=models.CASCADE)
    author=models.CharField(max_length=256)
    text=models.TextField()
    create_time=models.DateTimeField(default=timezone.now)
    approved_comment=models.BooleanField(default=False)


    def approve(self):
        self.approved_comment=True
        self.save()

    def get_absolute_url(self):
        return reverse('blog:postlist')
    def __str__(self):
        return self.text

clone/blog/forms.py
from django import forms
from blog.models import Post,comment

class postform(forms.ModelForm):
    class Meta():
        model= Post
        fields=('author','title','text')
        widgets={
        'title': forms.TextInput(attrs={'class':'textinputclass'}),
        'text': forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'})
        }

class commentform(forms.ModelForm):
    class Meta():
        model= comment
        fields=('author','text')
        widgets={
        'author':forms.TextInput(attrs={'class':'textinputclass'}),
        'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea'})
        }

clone/blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.utils import timezone
from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
from blog.models import Post,comment
from blog.forms import postform,commentform
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import  login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

# Create your views here.
class about(TemplateView):
    template_name="blog/about.html"

class postlist(ListView):
    context_object_name='postlist'
    model=Post
    template_name="blog/postlist.html"

    def get_queryset(self):
        return Post.objects.filter(pub_time__lte=timezone.now()).order_by('-pub_time')

class postdetail(DetailView):
    context_object_name='postdetail'
    model=Post
    template_name="blog/postdetail.html"

class postcreate(LoginRequiredMixin,CreateView):
    login_url='/login/'
    redirect_field_name='blog/postdetail.html'
    form_class = postform
    model=Post
    template_name="blog/postnew.html"

class postupdate(LoginRequiredMixin,UpdateView):
    login_url='/login/'
    redirect_field_name='blog/postdetail.html'
    form_class= postform
    model=Post
    template_name="blog/postnew.html"

class postdelete(DeleteView):
    model=Post
    success_url=reverse_lazy('blog:postlist')
    template_name='blog/postdelete.html'

class draftlist(LoginRequiredMixin,ListView):
    context_object_name='draftlist'
    login_url='/login/'
    redirect_field_name='blog/postlist.html'
    model=Post
    template_name='blog/draftlist.html'

    def get_queryset(self):
        return Post.objects.filter(pub_time__isnull=True).order_by('-create_time')

@login_required
def add_comment_to_post(request,pk):
    post = get_object_or_404(Post,pk=pk)
    if request.method == 'POST':
        form = commentform(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.post=post
            comment.save()
            return redirect('blog:postdetail',pk=post.pk)
    else:
        form=commentform()
    return render(request,'blog/commentform.html',{'form':form})


@login_required
def comment_approve(request,pk):
    com=get_object_or_404(comment,pk=pk)
    com.approve()
    return redirect('blog:postdetail',pk=com.post.pk)

@login_required
def comment_remove(request,pk):
    com=get_object_or_404(comment,pk=pk)
    post_pk=com.post.pk
    com.delete()
    return redirect('blog:postdetail',pk=post_pk)

@login_required
def post_publish(request,pk):
    pos=get_object_or_404(Post,pk=pk)
    Post.publish(pos)
    return redirect('blog:postdetail',pk=pk)

clone/blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block body_block %}
<h1>About This Company</h1>
<p>Thanks for Checking this out!</p>

{% endblock %}

clone/blog/templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Blog</title>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
     <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
     <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
     <link rel="stylesheet" href="{% static 'css/blog.css'%}">
     <link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One" rel="stylesheet">
  </head>
  <body class="loader">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark techfont custom-navbar">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand bigbrand" href="{% url 'blog:postlist' %}">My Blog  </a></li>
          <li class="nav-item"> <a class="nav-link" href="{% url 'blog:about' %}">  About   </a></li>
          <li class="nav-item"><a class="nav-link" href="https://www.github.com">  Github  </a></li>
          <li class="nav-item"><a class="nav-link" href="https://www.linkedin.com">  Linkedin  </a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}

             <li>
              <a class="nav-link" href="{% url 'blog:postnew' %}">New Post</a>
             </li>
             <li>
              <a class="nav-link" href="{% url 'blog:draftlist' %}">Draft</a>
             </li>
             <li>
              <a class="nav-link" href="{% url 'logout' %}"> Logout</a>
             </li>
             <li>
               <a class="nav-link">Welcome:{{user.username}}</a>
             </li>
          {% else %}
           <li>
             <a href="{% url 'login' %}">
               <span class="glyphicon glyphicon-user">Login</span>
             </a>
           </li>
          {% endif %}

        </ul>
      </div>

    </nav>
    <div class="content container">
      <div class="row">
        <div class="col-md-8">
          <div class="blog_post">
            {% block body_block %}
            {% endblock %}
          </div>

        </div>

      </div>

    </div>


  </body>
</html>

clone/blog/templates/blog/commentform.html
{% extends "blog/base.html" %}
{% block body_block %}
<h1>New Comment</h1>
 <form class="post-form" method="POST">
   {% csrf_token %}
   {{ form.as_p }}
   <button type="submit" class="save btn btn-primary" >Post Comment</button>
 </form>
 <script>var editor= new MediumEditor('.editable');
 </script>
{% endblock %}

clone/blog/templates/blog/draftlist.html
{% extends "blog/base.html" %}
{% block body_block %}
  {% for post in draftlist %}
    <div >
      <p class="date">Created: {{post.create_time|date:'D M Y'}}</p>
      <h1><a href="{% url 'blog:postdetail' pk=post.pk %}">{{post.title}}</a></h1>
      <p>{{post.text|truncatechars:200}}</p>
    </div>
  {% endfor %}

{% endblock %}

clone/blog/templates/blog/postdelete.html
{% extends "blog/base.html" %}
{% block body_block %}
 <form method="POST">
   {% csrf_token %}
   <p>Are you sure you want to delete {{object}}?</p>
   <input type="submit" class="btn btn-danger" value="Delete">
 </form>

{% endblock %}

clone/blog/templates/blog/postdetail.html
{% extends "blog/base.html" %}
{% block body_block %}
<h1 class="posttitle">{{postdetail.title}}</h1>
{% if postdetail.pub_time %}
 <div class="date postdate">
  {{postdetail.pub_time}}
 </div>
{% else %}
 <a class="btn btn-primary" href="{% url 'blog:post_publish' pk=postdetail.pk %}">Publish</a>
{% endif %}

<p class="postcontent">{{postdetail.text|safe|linebreaksbr}}</p>
{% if user.is_authenticated %}
 <a class="btn btn-primary "href="{% url 'blog:postedit' pk=postdetail.pk %}">
  <span class="glypicon glypicon-pencil">Edit</span></a>
 <a class="btn btn-primary "href="{% url 'blog:postdelete' pk=postdetail.pk %}">
  <span class="glypicon glypicon-remove">Delete</span></a>
{% endif %}
<hr>
<a class="btn btn-primary" href="{% url 'blog:add_comment_to_post' pk=postdetail.pk %}">Add Comment</a>
<div class="container">
  {% for comment in postdetail.comment.all %}
    <br>
     {% if user.is_authenticated or comment.approved_comment %}
       {{comment.create_time}}
       {% if not comment.approved_comment %}
        <a class="btn btn-primary "href="{% url 'blog:comment_approve' pk=comment.pk %}">
         <span class="glypicon glypicon-ok">approve</span></a>
        <a class="btn btn-primary "href="{% url 'blog:comment_remove' pk=comment.pk %}">
         <span class="glypicon glypicon-remove">remove</span></a>
       {% endif %}
       <p>{{comment.text|safe|linebreaksbr}}</p>
       <p>Posted By:{{comment.author}}</p>
     {% endif %}
     {% empty %}
     <p>No Comments!</p>
  {% endfor %}
</div>
{% endblock %}

clone/blog/templates/blog/postlist.html
{% extends "blog/base.html" %}
{% block body_block %}
<div class="centerstage">
  {% for post in postlist %}
   <div class="post">
     <h1><a href="{% url 'blog:postdetail' pk=post.pk %}">{{ post.title }}</a></h1>
    <div class="date">
      <p>Published On: {{post.pub_time|date:"D M Y"}}</p>
    </div>
    <a href="{% url 'blog:postdetail' pk=post.pk %}">Comment:{{ post.approve_comments.count }}</a>
  </div>
  {% endfor %}
</div>
{% endblock %}

clone/blog/templates/blog/postnew.html
{% extends "blog/base.html" %}
{% block body_block %}
  <h1>New Post</h1>
  <form class="post_form" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="save btn btn-primary ">Save </button>
  </form>
  <script>var editor= new MediumEditor('.editable');
  </script>

{% endblock %}